os: linux
dist: bionic
language: php

env:
  - PHP_CS_FIXER_IGNORE_ENV="true"

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - app/vendor

before_install:
  - nvm install 14.15
  - printf "\n" | pecl install -f apcu-5.1.18 memcached
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer update
  - npm ci

script:
  - npm run production --verbose
  - app/vendor/bin/php-cs-fixer fix --diff --dry-run
  - node_modules/.bin/eslint app/resources/js/**/*.{js,vue}
  - app/vendor/bin/psalm --show-info=true
  - app/vendor/bin/phpunit --coverage-text

before_deploy: make artifacts

deploy:
  on:
    tags: true
  provider: releases
  token: ${GITHUB_TOKEN}
  name: v${TRAVIS_TAG}
  tag_name: ${TRAVIS_TAG}
  draft: true
  file:
    - artifacts/DirectoryLister-${TRAVIS_TAG}.tar.gz
    - artifacts/DirectoryLister-${TRAVIS_TAG}.zip
  edge: true
