os: linux
dist: bionic
language: php

php:
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - app/vendor

install:
  - composer install
  - npm ci

script:
  - app/vendor/bin/php-cs-fixer fix --diff --dry-run
  - app/vendor/bin/psalm --show-info=true
  - app/vendor/bin/phpunit --coverage-text
  - npm run production
