version: '3.4'

services:
  app:
    container_name: directory-lister-app
    build: .
    environment:
      VIRTUAL_HOST: directory-lister.local
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP}

networks:
  default:
    external:
      name: development
